version: '3.4'
services:
  k6:
    image: loadimpact/k6:latest
    user: "${UID}:${GID}"
    sysctls:
      - net.ipv4.ip_local_port_range=1024 65535
      - net.ipv4.tcp_tw_reuse=1
      - net.ipv4.tcp_timestamps=1
    ulimits:
      nproc: 250000
      nofile:
        soft: 250000
        hard: 250000
    env_file:
      - .env
    command: run --out csv=results/${FEATURE}${TEST_TYPE}.csv --compatibility-mode=extended ${PROJECT}/${FEATURE}.js 
    working_dir: /app
    volumes:
      - ./:/app/:rw